backend:
  name: github
  repo: ybbarng/livvy.byb.kr
  branch: master # Branch to update (optional; defaults to master)
  base_url: https://blogauth.byb.kr

publish_mode: simple
media_folder: "/src/pages/images"
public_folder: "img"

accounts:
  - email: ybbarng@gmail.com
    auto_fields:
        authorId: ybbarng
  - email: bluenoche2@gmail.com
    auto_fields:
        authorId: livvy

collections:
  - name: "posts"
    label: "Article"
    folder: "src/pages/articles"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Cover Image", name: "image", widget: "image", required: false, tagname: ""}
      - {label: "Author ID", name: "authorId", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Draft", name: "draft", widget: "boolean", default: False}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ['test', 'test2']}
      - {label: "Tags", name: "tags", widget: "list", default: ""}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Page"
    folder: "src/pages/pages"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}/index"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Author ID", name: "authorId", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
